# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d7900970872eaffd044513348f650f46e79ae3cea235cb2440f104fe7b3dd923cbcb6be56b1817ed69caa2d9b14182ae9aa3b58dc068a85fb013e86a42aa9bb

test:
  secret_key_base: 0d91b49d13bd166a6ae954e10cbb53abe8e3572dc69fada9ce520def6471aaa5715500f38563092ea064b4d61484b17fe99d236005be6e9f6c4eda5218762855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
